/* Populated by react-webpack-redux:action */
export const FETCH_STREAM_REQUEST = 'FETCH_STREAM_REQUEST';
export const FETCH_STREAM_SUCCESS = 'FETCH_STREAM_SUCCESS';
export const FETCH_STREAM_FAILURE = 'FETCH_STREAM_FAILURE';
export const FETCH_SINGLE_ARTWORK_REQUEST = 'FETCH_SINGLE_ARTWORK_REQUEST';
export const FETCH_SINGLE_ARTWORK_SUCCESS = 'FETCH_SINGLE_ARTWORK_SUCCESS';
export const FETCH_SINGLE_ARTWORK_FAILURE = 'FETCH_SINGLE_ARTWORK_FAILURE';
export const ADD_ARTWORK = 'ADD_ARTWORK';
export const REMOVE_ARTWORK = 'REMOVE_ARTWORK';
export const EDIT_ARTWORK = 'EDIT_ARTWORK';
export const LIKE_ARTWORK = 'LIKE_ARTWORK';
export const PREVIEW_ARTWORK = 'PREVIEW_ARTWORK';
export const UNLIKE_ARTWORK = 'UNLIKE_ARTWORK';
export const PUSH_ARTWORK = 'PUSH_ARTWORK';

export const FETCH_FRAMES_REQUEST = 'FETCH_FRAMES_REQUEST';
export const FETCH_FRAMES_SUCCESS = 'FETCH_FRAMES_SUCCESS';
export const FETCH_FRAMES_FAILURE = 'FETCH_FRAMES_FAILURE';
export const SELECT_FRAME = 'SELECT_FRAME';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const FETCH_USER_ARTWORK_REQUEST = 'FETCH_USER_ARTWORK_REQUEST';
export const FETCH_USER_ARTWORK_SUCCESS = 'FETCH_USER_ARTWORK_SUCCESS';
export const FETCH_USER_ARTWORK_FAILURE = 'FETCH_USER_ARTWORK_FAILURE';
export const FETCH_USER_LIKES_REQUEST = 'FETCH_USER_LIKES_REQUEST';
export const FETCH_USER_LIKES_SUCCESS = 'FETCH_USER_LIKES_SUCCESS';
export const FETCH_USER_LIKES_FAILURE = 'FETCH_USER_LIKES_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE';
export const FETCH_CONFIG_REQUEST = 'FETCH_CONFIG_REQUEST';

export const FETCH_COLLECTIONS_REQUEST = 'FETCH_COLLECTIONS_REQUEST';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE';
export const FETCH_SINGLE_COLLECTION_REQUEST = 'FETCH_SINGLE_COLLECTION_REQUEST';
export const FETCH_SINGLE_COLLECTION_SUCCESS = 'FETCH_SINGLE_COLLECTION_SUCCESS';
export const FETCH_SINGLE_COLLECTION_FAILURE = 'FETCH_SINGLE_COLLECTION_FAILURE';

export const FETCH_CHANNELS_REQUEST = 'FETCH_CHANNELS_REQUEST';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';
export const FETCH_CHANNELS_FAILURE = 'FETCH_CHANNELS_FAILURE';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const PUSH_CHANNEL = 'PUSH_CHANNEL';
export const PUSH_COLLECTION = 'PUSH_COLLECTION';
export const OPEN_ARTWORK_DETAIL = 'OPEN_ARTWORK_DETAIL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_CREATE_ACCOUNT_MODAL = 'OPEN_CREATE_ACCOUNT_MODAL';
export const CLOSE_CREATE_ACCOUNT_MODAL = 'CLOSE_CREATE_ACCOUNT_MODAL';
export const OPEN_EDIT_PROFILE_MODAL = 'OPEN_EDIT_PROFILE_MODAL';
export const CLOSE_EDIT_PROFILE_MODAL = 'CLOSE_EDIT_PROFILE_MODAL';
export const SHOW_CONFIRM_DIALOG = 'SHOW_CONFIRM_DIALOG';
export const HIDE_CONFIRM_DIALOG = 'HIDE_CONFIRM_DIALOG';
