/* Populated by react-webpack-redux:action */
export const FETCH_STREAM_REQUEST = 'FETCH_STREAM_REQUEST';
export const FETCH_STREAM_SUCCESS = 'FETCH_STREAM_SUCCESS';
export const FETCH_STREAM_FAILURE = 'FETCH_STREAM_FAILURE';
export const FETCH_SINGLE_ARTWORK_REQUEST = 'FETCH_SINGLE_ARTWORK_REQUEST';
export const FETCH_SINGLE_ARTWORK_SUCCESS = 'FETCH_SINGLE_ARTWORK_SUCCESS';
export const FETCH_SINGLE_ARTWORK_FAILURE = 'FETCH_SINGLE_ARTWORK_FAILURE';
export const LIKE_ARTWORK_REQUEST = 'LIKE_ARTWORK_REQUEST';
export const LIKE_ARTWORK_SUCCESS = 'LIKE_ARTWORK_SUCCESS';
export const LIKE_ARTWORK_FAILURE = 'LIKE_ARTWORK_FAILURE';
export const UNLIKE_ARTWORK_REQUEST = 'UNLIKE_ARTWORK_REQUEST';
export const UNLIKE_ARTWORK_SUCCESS = 'UNLIKE_ARTWORK_SUCCESS';
export const UNLIKE_ARTWORK_FAILURE = 'UNLIKE_ARTWORK_FAILURE';
export const ADD_ARTWORK = 'ADD_ARTWORK';
export const REMOVE_ARTWORK = 'REMOVE_ARTWORK';
export const EDIT_ARTWORK = 'EDIT_ARTWORK';
export const PREVIEW_ARTWORK = 'PREVIEW_ARTWORK';
export const PUSH_ARTWORK = 'PUSH_ARTWORK';
export const LOADING_IMAGES = 'LOADING_IMAGES';

export const EDIT_FRAME_SETTINGS = 'EDIT_FRAME_SETTINGS';
export const FETCH_FRAMES_REQUEST = 'FETCH_FRAMES_REQUEST';
export const FETCH_FRAMES_SUCCESS = 'FETCH_FRAMES_SUCCESS';
export const FETCH_FRAMES_FAILURE = 'FETCH_FRAMES_FAILURE';
export const SELECT_FRAME = 'SELECT_FRAME';
export const UPDATE_FRAME_REQUEST = 'UPDATE_FRAME_REQUEST';
export const UPDATE_FRAME_SUCCESS = 'UPDATE_FRAME_SUCCESS';
export const UPDATE_FRAME_FAILURE = 'UPDATE_FRAME_FAILURE';
export const DELETE_FRAME_REQUEST = 'DELETE_FRAME_REQUEST';
export const DELETE_FRAME_SUCCESS = 'DELETE_FRAME_SUCCESS';
export const DELETE_FRAME_FAILURE = 'DELETE_FRAME_FAILURE';
export const UPDATE_FRAME_MANAGERS_REQUEST = 'UPDATE_FRAME_MANAGERS_REQUEST';
export const UPDATE_FRAME_MANAGERS_SUCCESS = 'UPDATE_FRAME_MANAGERS_SUCCESS';
export const UPDATE_FRAME_MANAGERS_FAILURE = 'UPDATE_FRAME_MANAGERS_FAILURE';
export const UPDATE_CURRENT_ARTWORK_REQUEST = 'UPDATE_CURRENT_ARTWORK_REQUEST';
export const UPDATE_CURRENT_ARTWORK_SUCCESS = 'UPDATE_CURRENT_ARTWORK_SUCCESS';

export const FRAME_UPDATED = 'FRAME_UPDATED';  // pubsub

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const FETCH_USER_ARTWORK_REQUEST = 'FETCH_USER_ARTWORK_REQUEST';
export const FETCH_USER_ARTWORK_SUCCESS = 'FETCH_USER_ARTWORK_SUCCESS';
export const FETCH_USER_ARTWORK_FAILURE = 'FETCH_USER_ARTWORK_FAILURE';
export const FETCH_USER_LIKES_REQUEST = 'FETCH_USER_LIKES_REQUEST';
export const FETCH_USER_LIKES_SUCCESS = 'FETCH_USER_LIKES_SUCCESS';
export const FETCH_USER_LIKES_FAILURE = 'FETCH_USER_LIKES_FAILURE';
export const REMOVE_FROM_FRAME_REQUEST = 'REMOVE_FROM_FRAME_REQUEST';
export const REMOVE_FROM_FRAME_SUCCESS = 'REMOVE_FROM_FRAME_SUCCESS';
export const REMOVE_FROM_FRAME_FAILURE = 'REMOVE_FROM_FRAME_FAILURE';
export const INITIATE_UPDATE_PROFILE = 'INITIATE_UPDATE_PROFILE';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';

export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE';
export const FETCH_CONFIG_REQUEST = 'FETCH_CONFIG_REQUEST';

export const FETCH_COLLECTIONS_REQUEST = 'FETCH_COLLECTIONS_REQUEST';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE';
export const FETCH_SINGLE_COLLECTION_REQUEST = 'FETCH_SINGLE_COLLECTION_REQUEST';
export const FETCH_SINGLE_COLLECTION_SUCCESS = 'FETCH_SINGLE_COLLECTION_SUCCESS';
export const FETCH_SINGLE_COLLECTION_FAILURE = 'FETCH_SINGLE_COLLECTION_FAILURE';

export const FETCH_CHANNELS_REQUEST = 'FETCH_CHANNELS_REQUEST';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';
export const FETCH_CHANNELS_FAILURE = 'FETCH_CHANNELS_FAILURE';

export const CLOSE_NOTICE_BANNER = 'CLOSE_NOTICE_BANNER';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const PUSH_CHANNEL = 'PUSH_CHANNEL';
export const PUSH_COLLECTION = 'PUSH_COLLECTION';
export const OPEN_ARTWORK_DETAIL = 'OPEN_ARTWORK_DETAIL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_CREATE_ACCOUNT_MODAL = 'OPEN_CREATE_ACCOUNT_MODAL';
export const CLOSE_CREATE_ACCOUNT_MODAL = 'CLOSE_CREATE_ACCOUNT_MODAL';
export const OPEN_EDIT_PROFILE_MODAL = 'OPEN_EDIT_PROFILE_MODAL';
export const CLOSE_EDIT_PROFILE_MODAL = 'CLOSE_EDIT_PROFILE_MODAL';
export const SHOW_CONFIRM_DIALOG = 'SHOW_CONFIRM_DIALOG';
export const HIDE_CONFIRM_DIALOG = 'HIDE_CONFIRM_DIALOG';
export const SHOW_CREATE_ACCOUNT_NOTICE = 'SHOW_CREATE_ACCOUNT_NOTICE';
export const HIDE_CREATE_ACCOUNT_NOTICE = 'HIDE_CREATE_ACCOUNT_NOTICE';
export const OPEN_STATEFUL_MODAL = 'OPEN_STATEFUL_MODAL';
export const CLOSE_STATEFUL_MODAL = 'CLOSE_STATEFUL_MODAL';
export const OPEN_FRAME_SETTINGS_MODAL = 'OPEN_FRAME_SETTINGS_MODAL';
export const CLOSE_FRAME_SETTINGS_MODAL = 'CLOSE_FRAME_SETTINGS_MODAL';
export const FIX_BODY = 'FIX_BODY';
export const UNFIX_BODY = 'UNFIX_BODY';


export const UPDATE_VISIBLE_MODAL = 'UPDATE_VISIBLE_MODAL';
export const UPDATE_SIDEBAR_STATE = 'UPDATE_SIDEBAR_STATE';
export const UPDATE_NOTICE_BANNER = 'UPDATE_NOTICE_BANNER';

export const SET_FEATURE_FLAG = 'SET_FEATURE_FLAG';